# name: Deploy Static Application to Ubuntu Apache2 Server
# on:

#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


#   workflow_dispatch:


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build Step
#         run: echo "Build Step"


#   test:
#     runs-on: ubuntu-latest
#     needs: build  
#     steps:
#       - name: Test Step
#         run: echo "Test Step"
  
  
#   deployment:
#     runs-on: ubuntu-latest
#     needs: test
#     environment:
#       name: main
#       url: http://20.231.36.179/contact.html

#     steps:
#       - name: Clone the Code
#         uses: actions/checkout@v3

#       - name: Verify the Code is Cloned
#         run: ls -la
#       - name: 
#         uses: mdallasanta/ssh-scp-deploy@v1.2.0
#         with:
#           local: './'                                                  # Local file path - REQUIRED false - DEFAULT ./
#           remote: '/home/azureuser'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
#           host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
#           port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
#           user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
#           #password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
#           key: ${{secrets.SERVER_SSH_KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
#           pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
#           post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
#           ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
#           scp_options: -v                                              # Flags to use during scp - REQUIRED false - DEFAULT ''

name: Deploy Static Application to Ubuntu Apache2 Server
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env: 
  myapp_ver: "1.0.0"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone the Code
        uses: actions/checkout@v3
        
      - name: Build Step
        run: echo "Build Step"

      - name: Inject Version Details to the Application
        run: |
          pwd
          ls -la
          sed -i "s/REPLACEAPPLICATIONENVIRONMENT/${myapp_ver}/g" ./myapp/version.html
          cat myapp/version.html

      - name: Upload the Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-package
          path: myapp
  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Test Step
        run: echo "Test Step"
      
      - name: Download the myapp-package
        uses: actions/download-artifact@v3
        with:
          name: myapp-package
          path: myapp

      - name: Verify the downloaded Packages
        run: |
          ls -la
          pwd

      - name: Cat the file and test for replacement.
        run: cat myapp/version.html
  
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test
    environment:
      name: development
      url: http://20.231.36.179/mysite.html

    steps:
      - name: Clone the Code
        uses: actions/checkout@v3

      - name: Download the myapp-package
        uses: actions/download-artifact@v3
        with:
          name: myapp-package
          path: myapp

      - name: Verify the Code is Cloned
        run: ls -la

      # - name: Copy the Code to the Server
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-rltgoDzvO"
      #     SOURCE: "myapp"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}

      # - name: Move the file from Home Directory to Apache Dir on Remote Ubuntu Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     script: sudo mv myapp/* /var/www/html/

      - name: Copy the Index.html to Ubuntu Server
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'myapp'
          remote: '/home/azureuser/'
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SERVER_SSH_KEY}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: echo "remove the files"
          post_upload: sudo mv myapp/* /var/www/html/