name: Deploy Static Application to Ubuntu Apache2 Server
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Build Step"


  test:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Test Step
        run: echo "Test Step"
  
  
  deployment:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: main
      url: http://20.231.36.179/contact.html

    steps:
      - name: Clone the Code
        uses: actions/checkout@v3

      - name: Verify the Code is Cloned
        run: ls -la
      - name: 
        uses: mdallasanta/ssh-scp-deploy@{version}
        with:
          local: './'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
          port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.REMOTE_USER}}                                      # Remote server user - REQUIRED true
          #password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key" 
          key: ${{secrets.SERVER_SSH_KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
          pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v                                              # Flags to use during scp - REQUIRED false - DEFAULT ''