name: Deploy Static Application to Ubuntu Apache2 Server
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  deployment:

    runs-on: ubuntu-latest

    steps:
      - name: Clone the Code
        uses: actions/checkout@v3

      - name: Verify the Code is Cloned
        run: ls -la

      - name: Copy the Code to the Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "mysite.html"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET}}
      
      - name: deploy files to Azure server
        uses: ilCollez/ssh-scp-deploy@main
        with:
          host: ${{ secrets.REMOTE_HOST }} # "example.com"
          #port: ${{ secrets.SSH_PORT }} # 22
          username: ${{ secrets.REMOTE_USER }} # "user"
          key: ${{ secrets.SERVER_SSH_KEY }} # "~/.ssh/id_rsa", can also be the key itself
          #passphrase: ${{ secrets.SSH_PASSPHRASE }} # "passphrase"
          files: |
            *.html
          remote-path: ${{ secrets.REMOTE_TARGET}}

      - name: move file to 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          #port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
            pwd
            sudo mv *.html /var/www/html/